/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { MessagesRequestBuilderRequestsMetadata, type MessagesRequestBuilder } from './messages/index.js';
// @ts-ignore
import { PromptRequestBuilderRequestsMetadata, type PromptRequestBuilder } from './prompt/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/users/{userId}/conversations/{conversationId}
 */
export interface WithConversationItemRequestBuilder extends BaseRequestBuilder<WithConversationItemRequestBuilder> {
    /**
     * The messages property
     */
    get messages(): MessagesRequestBuilder;
    /**
     * The prompt property
     */
    get prompt(): PromptRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithConversationItemRequestBuilderUriTemplate = "{+baseurl}/api/users/{userId}/conversations/{conversationId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithConversationItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithConversationItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    messages: {
        requestsMetadata: MessagesRequestBuilderRequestsMetadata,
    },
    prompt: {
        requestsMetadata: PromptRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithConversationItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithConversationItemRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
