/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ConversationsRequestBuilderNavigationMetadata, ConversationsRequestBuilderRequestsMetadata, type ConversationsRequestBuilder } from './conversations/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/users/{userId}
 */
export interface WithUserItemRequestBuilder extends BaseRequestBuilder<WithUserItemRequestBuilder> {
    /**
     * The conversations property
     */
    get conversations(): ConversationsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithUserItemRequestBuilderUriTemplate = "{+baseurl}/api/users/{userId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithUserItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithUserItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    conversations: {
        requestsMetadata: ConversationsRequestBuilderRequestsMetadata,
        navigationMetadata: ConversationsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
