/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAIModelFromDiscriminatorValue, type AIModel } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/models
 */
export interface ModelsRequestBuilder extends BaseRequestBuilder<ModelsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AIModel[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AIModel[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ModelsRequestBuilderUriTemplate = "{+baseurl}/api/models";
/**
 * Metadata for all the requests in the request builder.
 */
export const ModelsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ModelsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createAIModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
